DevElevate/src/components/Auth/LoginRegister.tsx
fixes issue #2 
name: Added a Password strength checker
about: Integrate a real-time password strength checker into the current signup form to enhance security and help users create stronger passwords.
Adds a visual password strength meter and instant feedback below the password input. Ensure seamless integration with the existing UI/UX design.
Please delete options that are not relevant:
=> Add password strength checking logic

DevElevate/Client/src/components/ResumeBuilder/ResumeBuilder.tsx, DevElevate/Client/src/components/ResumeBuilder/ResumePreview.tsx
---
[Click here to watch the demo video](https://drive.google.com/file/d/1b5btCUGv0EYzGYPHX23uUgenGvCZhfIh/view?usp=sharing)
This feature introduces a **"Download PDF** button on the Resume Builder page. It allows users to **download their resume as a PDF**, enhancing user experience by providing easy access to their data.
---
> The feature adds a functional download option on the Resume Builder page. When clicked, it generates a `.pdf` of the user's resume dynamically and prompts a download.
---
- **Location:** `Client\src\components\ResumeBuilder\ResumeBuilder.tsx` 
- **Libraries Used:** `jsPDF`, `html2canvas`  
- **Trigger:** Button labeled **Download pdf**  
- **Output:** Downloadable `.pdf` file containing resume content  
---
1. User navigates to the resume builder.
2. The …
=> Added Resume download feature

DevElevate/Client/src/components/Admin/AdminDashboard.tsx, DevElevate/Client/src/components/Chatbot/Chatbot.tsx, DevElevate/Client/src/components/Layout/ProfileDropdown.tsx, DevElevate/Client/src/utils/helperAI.ts
---
Riya Chandra: 🛠️ Pull Request
about: Submit a pull request for code & or feature enhancement
title: '[PR] Fix: Bug in the dashboard & Feature: AI Chatbot quiz feature addition '
Issue:#99
assignees: 'Riya-chandra'
---
[99] Feature: Integrated Gemini-Based Quiz Generation in Chatbot
Description:
This PR introduces an advanced AI-powered quiz generation feature within the Study Buddy chatbot using Gemini 2.0 Flash.
When users select the "quiz" category and input a topic (e.g., Binary Search, Graphs), the chatbot now dynamically generates 6 in-depth, DSA-focused multiple-choice questions related to that topic.
The logic intelligently distinguishes between quiz and non-quiz categories to ensure that question generation occurs only when relevant.
This …
=> [BUG] & [FEATURE]: Chatbot advancement and dashboard bug

DevElevate/Client/package-lock.json, DevElevate/Client/src/App.tsx, DevElevate/Client/src/components/Settings/Settings.tsx
---
title: '[PR] ✨ Added: Settings page with routing and gradient heading'
assignees: 'Coder-010506'
---
> This PR adds a new **Settings page** component to the project.  
> It includes routing integration and improving user navigation and UI consistency.
---
Fixes #94 
---
---
---
*(Include a screenshot if applicable or required)*
---
- Check for correct route integration in `App.tsx`  
---
> ✅ PRs that follow structure and clarity help speed up reviews!
=> Settings page

DevElevate/Client/src/components/PlacementPrep/PlacementPrep.tsx
title: '[PR] 🐛 Bug fix: Job filtering and emoji input added to PlacementPrep'
assignees: @Nagasrineelamshetty 
---
#Pull Request Details
This PR resolves Issue #35 by adding a debounced search bar and category filter in the PlacementPrep.tsx file.
It enhances the user experience by allowing users to filter job opportunities based on role, tech stack, company, or description.
A search emoji icon has also been added inside the input field for improved UI clarity.
The filtering works in both light and dark modes, and includes accessibility-friendly design updates.
---
This PR fixes the PlacementPrep.tsx UI by adding a search bar and improving the filtering …
=> fix: resolved job filtering by adding a search bar in PlacementPrep.tsx

DevElevate/Client/src/components/Chatbot/Chatbot.tsx
name: 🛠️ Pull Request  
about: Submit a pull request for code, documentation, or feature enhancement  
title: '[PR] fix(chat): scroll-to-bottom logic corrected for better UX'  
labels: 'pull-request', 'under review'  
assignees: ''
---
This PR fixes the chat scroll behavior. Previously, when a message was sent, the auto-scroll would overshoot, causing the latest AI message to be hidden or partially visible.  
We now use `messagesEndRef.scrollIntoView({ behavior: "smooth" })` to reliably scroll to the last message without excessive jumpiness.
---
Fixes #<replace-with-issue-number> (if tracked in issues)
---
---
---
_N/A — functional fix, no UI changes._
---
Focus on the scroll behavior of the chat window when a new message is rendered. …
=> Fixed scrolling to the end of page

DevElevate/Client/package-lock.json, DevElevate/Client/package.json, DevElevate/Client/src/components/Dashboard/NewsWidget.tsx, DevElevate/Client/src/components/Dashboard/ProgressWidget.tsx
---
- This  PR solves the issue of redirecting to view all button of learning progress to learnhub page `/learning`
- Also this PR solves issue of redirecting to page to view all tech feed from dashboard `/news`
---
Fixes #107  
---
Please delete options that are not relevant:
---
---
Paste screenshots or a screen recording of the feature/bug fix.
https://github.com/user-attachments/assets/56453f10-d963-4bc2-ba49-40c27ae1a815
---
Mention anything that reviewers should focus on or be aware of.
Please add my Name and point for the contribution
---
> ✅ PRs that follow the structure and guidelines are reviewed and merged faster!
=> fix: redirect of learning progress and  news & update 

DevElevate/Client/package-lock.json, DevElevate/Client/src/App.tsx, DevElevate/Client/src/components/Admin/AdminDashboard.tsx, DevElevate/Client/src/components/Admin/AdminSystemLogs.tsx, DevElevate/Client/src/contexts/AuthContext.tsx, DevElevate/Client/test-jwt.js, DevElevate/Server/.env.example, DevElevate/Server/controller/adminLogController.js, DevElevate/Server/controller/userController.js, DevElevate/Server/create-test-logs.js, DevElevate/Server/index.js, DevElevate/Server/middleware/authMiddleware.js, DevElevate/Server/model/AdminLog.js, DevElevate/Server/package-lock.json, DevElevate/Server/package.json, DevElevate/Server/routes/adminRoutes.js, DevElevate/Server/test-admin.js
---
name: issue #74 
title: 'Admin System log Viewer'
assignees: 
NamanSoni18
---
🔐 Admin Authentication System
1. JWT-based authentication with real backend integration
2. Role-based access control (admin-only access to /admin/logs)
3. Fixed browser compatibility issues with proper API calls
📊 System Logs Dashboard
1. Real-time log display with filtering (action type, date)
2. Pagination support (20 logs per page)
3. Responsive UI with dark/light mode support
🗄️ MongoDB Integration
1. AdminLog collection with indexed schema
2. 13 predefined action types (login, logout, view_logs, etc.)
3. Automatic timestamp and IP tracking
🔄 Automatic Log Generation
1. Auto-logs on …
=> Integrated Admin System Logs Viewer #74

DevElevate/Server/middleware/Validators.js, DevElevate/Server/package-lock.json, DevElevate/Server/package.json, DevElevate/Server/routes/userRoutes.js
---
about: Submit a pull request for code
title: Added zod validators for signup and login routes
assignees: @abhisek2004 
---
This pull request adds robust input validation middleware using the Zod library for the signup and login routes. The goal is to ensure that all incoming requests to these endpoints are properly validated before reaching the business logic.
✅ What's Included:
name: Required, non-empty string
email: Must be a valid email
password: Minimum 6 characters
role: Must be either "user" or "admin"
email: Must be a valid email
password: Minimum 6 characters
**signUpValidator** :  Validates request body against signupSchema
**loginValidator** :  Validates request body against loginSchema
_Proper error response (400 …
=> Add Zod-based Input Validation for Signup and Login Routes

DevElevate/Client/package-lock.json, DevElevate/Client/src/components/Dashboard/DailyGoals.tsx, DevElevate/Client/src/components/Dashboard/Dashboard.tsx, DevElevate/Client/src/components/Dashboard/NewsWidget.tsx, DevElevate/Client/src/components/Dashboard/ProgressWidget.tsx, DevElevate/Client/src/components/Dashboard/QuickActions.tsx, DevElevate/Client/src/components/Dashboard/StatsCards.tsx, DevElevate/Client/src/components/Dashboard/StreakCalendar.tsx, DevElevate/Client/src/components/LearningHub/LearningHub.tsx, DevElevate/Client/src/components/PlacementPrep/PlacementPrep.tsx, DevElevate/Client/src/components/ResumeBuilder/EducationForm.tsx, DevElevate/Client/src/components/ResumeBuilder/ExperienceForm.tsx, DevElevate/Client/src/components/ResumeBuilder/PersonalInfoForm.tsx, DevElevate/Client/src/components/ResumeBuilder/ProjectsForm.tsx, DevElevate/Client/src/components/ResumeBuilder/ResumeBuilder.tsx, DevElevate/Client/src/components/ResumeBuilder/SkillsForm.tsx, DevElevate/Client/src/components/TechFeed/TechFeed.tsx
=> UI updates

DevElevate/Client/src/App.tsx, DevElevate/Client/src/components/Dashboard/NewsWidget.tsx, DevElevate/Client/src/components/Dashboard/ProgressWidget.tsx, DevElevate/Client/src/components/Layout/Navbar.tsx, DevElevate/Client/src/components/Layout/NotificationPanel.tsx, DevElevate/Client/src/components/PlacementPrep/PlacementPrep.tsx, DevElevate/Client/src/contexts/GlobalContext.tsx, DevElevate/Client/src/contexts/NotificationContext.tsx, DevElevate/Client/src/index.css, DevElevate/Server/index.js, DevElevate/Server/middleware/authMiddleware.js, DevElevate/Server/routes/courseRoutes.js
---
about: Submit a pull request for code bug fixes
title: '[PR] bug fixes: The notifications panel was not scrollable, causing users to miss unread or older notifications.
Additionally, the unread notification count was not updating properly on the dashboard.'
assignees: ''
---
This PR has fixed the below issues:
- The notifications panel is currently not scrollable, causing users to miss unread or older notifications.
- Additionally, the unread notification count is not updating properly on the dashboard.
Also there were some minor changes needed for the code to run like some elemnt fixes which I have done.
> This PR adds the course upload module to the admin panel, allowing instructors to upload video content and attach …
=> Notifcation bug fixes and minor adjustments

DevElevate/Client/package-lock.json, DevElevate/Client/package.json, DevElevate/Client/src/components/Admin/AdminDashboard.tsx, DevElevate/Client/src/components/Admin/AdminFeedback.tsx, DevElevate/Client/src/utils/axiosinstance.ts, DevElevate/Server/controller/feedbackController.js, DevElevate/Server/index.js, DevElevate/Server/model/feedback.js, DevElevate/Server/routes/adminFeedbackRoutes.js
title: '[PR] <type>: <short description>'
assignees: @Isha-upadhyay 
---
Backend Endpoints:
- GET /admin/feedback/all – Get all feedbacks
- PATCH /admin/feedback/:id/reviewed – Mark feedback as reviewed
- DELETE /admin/feedback/:id – Delete feedback
- All routes protected by admin token (via Authorization header)
Frontend: AdminFeedback.tsx
- View all submitted user feedback
- Display user email + avatar
- Show feedback status: Pending or Reviewed
Admin can:
✅ Mark as Reviewed
❌ Delete feedback
---
Fixes #70 
---
---
---
All dummy feedback removed – now fully dynamic via DB
@abhisek2004 @Avansh2006 Please review this PR.
✅ PRs that follow the structure …
=> [Feature] & [Enhancement]: Feedback Moderation Page (Admin Panel) and add filter

DevElevate/Client/src/components/Profile/UserProfile.tsx
added placeholders to be filled if the cancel button is pressed...used a dedicated function handleCancelEdit to clear and reset the form data
---
title: '[PR] <type>: <short description>'
assignees: ''
---
> This PR adds the course upload module to the admin panel, allowing instructors to upload video content and attach downloadable PDFs.
---
Fixes #<issue-number> (if applicable)
---
Please delete options that are not relevant:
---
---
Paste screenshots or a screen recording of the feature/bug fix.
---
Mention anything that reviewers should focus on or be aware of.
---
> ✅ PRs that follow the …
=> fixed issue #121 cancel button functionality in edit mode has been fixed

DevElevate/Client/src/components/Auth/LoginRegister.tsx, DevElevate/Client/src/contexts/AuthContext.tsx, DevElevate/Client/src/utils/axiosinstance.ts, DevElevate/Server/.env, DevElevate/Server/controller/userController.js, DevElevate/Server/routes/userRoutes.js
✅ **Merge Message:**
```
[BUG + FEATURE] Complete User/Admin Auth System with Secure Data Storage + Welcome Email Flow #109
✅ Fixed login & register bugs
✅ Role-based access (User/Admin) completed
✅ Secure data storage using hashed passwords and JWT
✅ Role toggle UI improved for clarity
✅ Welcome email flow integrated post-registration
✅ Frontend and backend integration stabilized
```
You can now **merge it confidently** — the core Auth system is ready for production with role-based access and improved UX! 🚀
=> login , register , admin , user fixed

DevElevate/Client/src/components/Admin/AdminDashboard.tsx, DevElevate/Client/src/components/Layout/Footer.tsx
> This PR improves the existing footer design by addressing spacing, alignment, and icon styling issues.  
> The updated footer includes consistent font and icon sizes, proper spacing between elements, and smooth hover effects for enhanced UI experience.  
> These changes align with the design feedback from the related issue and give the footer a more professional and polished appearance.
---
---
---
Please focus on:
- Consistency in spacing and font size
- Smoothness of hover transitions
- Mobile responsiveness of the footer layout
=> 🐛 Bug fix: Improved footer spacing, alignment, and hover effects

DevElevate/Client/src/App.tsx, DevElevate/Client/src/components/Chatbot/Chatbot.tsx, DevElevate/Client/src/components/Layout/ScrollToTop.tsx, DevElevate/Client/src/utils/useScrollToTop.ts
---
Name: 🛠️ Pull Request
About: Submit a pull request for code, documentation, or feature enhancement
Title: '[PR] 🐛 fix: Scroll Position Persistence Across Navigation'
Labels: 'pull-request', 'under review'
---
> This PR addresses an inconsistent scroll behavior issue across the application. When users navigated between navbar items (e.g., Dashboard → Study Buddy), the new page retained the scroll position of the previous page, creating a disorienting and poor user experience.
> Created a global scroll restoration system by implementing a ScrollToTop component (src/components/Layout/ScrollToTop.tsx) that uses useLocation hook to detect route changes and automatically scrolls the window to the top (0, 0) with smooth behavior for better UX.
> Integrated the component into the main App …
=> Fixed Issue Number-148

DevElevate/Client/.env.example, DevElevate/Client/.gitignore, DevElevate/Client/src/App.tsx, DevElevate/Client/src/components/Layout/Navbar.tsx, DevElevate/Client/src/components/ProjectRecommender/CommunityShowcase.tsx, DevElevate/Client/src/components/ProjectRecommender/PreferenceForm.tsx, DevElevate/Client/src/components/ProjectRecommender/ProjectCard.tsx, DevElevate/Client/src/components/ProjectRecommender/ProjectRecommender.tsx, DevElevate/Client/src/utils/groqAPI.ts, DevElevate/Client/src/utils/projectStorage.ts
---
title: '[PR] ✨ Feature: AI-Based Project Recommender for Personalized Skill Growth'
assignees: 'Coder-010506'
---
> This PR introduces an AI-Based Project Recommender module that helps users discover project ideas tailored to their preferences. Users can fill out a short form including known tech stack, career focus, skill level, and interest areas. Based on their input, the app fetches 3–5 curated project suggestions using an AI API (Groq/OpenAI).
**Key Highlights:**
- User preference form: multi-select and dropdowns for tech stack, skill, and interests
- Dynamic project generation using AI API
- Displays project title, description, features, tags, …
=> adding feature of ai project recommandation

Make Enchance ui
This pull request introduces a redesigned and bold-styled user interface for the Tech News & Opportunities section of the application. The goal of this enhancement is to improve readability, user engagement, and visual hierarchy using Tailwind CSS and shadcn/ui components.
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>CodeLeet - Coding Platform</title>
<script src="https://cdn.tailwindcss.com"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
<style>
/* Custom scrollbar */
::-webkit-scrollbar {
width: 8px;
height: 8px;
}
::-webkit-scrollbar-track {
background: #f1f1f1;
}
::-webkit-scrollbar-thumb {
background: #888;
border-radius: …
=> Create Make Enchance ui

DevElevate/Client/src/App.tsx
> This PR fixes an issue where navigating to unknown routes did not redirect the user properly. Now, all undefined paths are routed to the dashboard, ensuring smoother navigation and error handling.
---
Fixes #158
---
Please delete options that are not relevant:
---
---
https://github.com/user-attachments/assets/e1e189dc-ee61-4720-b995-b090bd1702a0
---
This issue was labeled as `level 2`, and I have put in significant effort — changes required modifying routing logic and verifying fallback behavior.  
I’m submitting this as part of **GSSoC**, and I hope this earns me some more points!  
Kindly review and merge it soon. 🙌
---
> ✅ PRs that follow the structure and guidelines are reviewed and merged faster!
=> Fix: Route unknown paths to dashboard

DevElevate/Client/src/components/Dashboard/NewsWidget.tsx, DevElevate/Client/src/components/Layout/Footer.tsx, DevElevate/Client/src/contexts/AuthContext.tsx
=> add live link  to the  footer and fix bug in  news feed

DevElevate/Client/package-lock.json, DevElevate/Client/package.json, DevElevate/Client/src/components/Auth/LoginRegister.tsx, DevElevate/Client/src/config/routes.js, DevElevate/Client/src/config/routes.ts, DevElevate/Client/src/contexts/AuthContext.tsx, DevElevate/Client/src/utils/firebase.ts, DevElevate/Server/controller/userController.js, DevElevate/Server/routes/userRoutes.js
---
title: '[PR]✨ New feature : Add Google Login using Firebase Authentication'
assignees:  @abhisek2004 
---
This PR adds Google Login using Firebase Authentication to the existing authentication system, which currently supports only email login. It allows users to securely sign in with their Google accounts, improving user convenience and onboarding speed without compromising security
**(Additional update)**
Updated frontend API calls to use the correct baseUrl configuration, preventing the /api/v1 path segment from being duplicated in the request URLs. This ensures proper API endpoint targeting and avoids potential communication errors.
---
Fixes …
=> Add Google Login using Firebase Authentication

DevElevate/Client/package-lock.json, DevElevate/Client/package.json, DevElevate/Client/src/components/Auth/ProtectedRoute.tsx, DevElevate/Server/.env.sample
**final admin redirect to admin page**
=> final admin redirect to admin page

DevElevate/Client/src/App.tsx, DevElevate/Client/src/api/adminApi.ts, DevElevate/Client/src/api/axiosinstance.ts, DevElevate/Client/src/components/Admin/AdminDashboard.tsx, DevElevate/Client/src/components/Admin/AdminFeedback.tsx, DevElevate/Client/src/contexts/AdminContext.tsx, DevElevate/Client/src/contexts/AuthContext.tsx, DevElevate/Client/src/types/User.ts, DevElevate/Server/controller/adminLogController.js, DevElevate/Server/controller/userController.js, DevElevate/Server/index.js, DevElevate/Server/middleware/authMiddleware.js, DevElevate/Server/routes/adminRoutes.js, DevElevate/Server/routes/courseRoutes.js, DevElevate/Server/routes/userRoutes.js
=> database all user data show in the admin panel

DevElevate/Client/src/api/axiosinstance.ts, DevElevate/Client/src/contexts/AuthContext.tsx
=> Update axios instance to use dynamic base URL from config

DevElevate/Client/vercel.json
404: NOT_FOUND  
Code: NOT_FOUND  
ID: bom1::5779p-1754281465537-f251fab7ae35
=> Title: 404 NOT_FOUND error on Vercel reload for React Router / Vite app

DevElevate/Server/controller/userController.js, DevElevate/Server/package-lock.json, DevElevate/Server/package.json, DevElevate/Server/utils/mailer.js, DevElevate/Server/utils/welcomeTemplate.js
=> Add user registration email functionality with welcome template

DevElevate/Client/src/components/Dashboard/NewsWidget.tsx, DevElevate/Client/src/components/Layout/ProfileDropdown.tsx, DevElevate/Server/controller/userController.js, DevElevate/Server/routes/userRoutes.js
=> feat: implement latest news fetching and update backend side

DevElevate/Server/controller/userController.js
As described in issue #289, the Learning Streak count was not updating for users upon completion of a daily activity. This was caused by a backend error in the streak calculation logic that prevented the new streak data from being saved correctly.
This PR addresses the issue by making the following changes to the `currentStreak` function in `userController.js`:
1.  **Corrected Data Handling:** Fixed a critical bug where the application was mixing data types (an object ID string into an array of full objects), causing the calculation to fail. The logic now consistently uses full objects, ensuring stability.
2.  **Improved Calculation Logic:** The algorithm for calculating the `currentStreak` and `longestStreak` has been rewritten to be more accurate and robust. It now correctly handles …
=> Fix(streak): Resolve issue #289 where learning streak fails to update

DevElevate/Server/controller/userController.js, DevElevate/Server/model/UserModel.js
=> minimum 8 characters and no maximum limit,

DevElevate/Client/src/components/Dashboard/DailyGoals.tsx, DevElevate/Client/src/components/Dashboard/Dashboard.tsx, DevElevate/Client/src/components/Dashboard/StreakCalendar.tsx, DevElevate/Client/src/components/Profile/UserProfile.tsx
**Have you starred the repository?**
---
Integrated and fixed the Learning Streak backend logic to properly track user daily learning activities. The streak counting system now correctly increments for consecutive days and resets appropriately when users miss activities. Updated dashboard and profile components to reflect real-time streak data with improved user experience.
**Related Issue(s):**
- Fixes #289 
---
---
---
---
---
---
---
@abhisek2004
=> Integrated Learning Streak Backend with Frontend #289 Level 2

DevElevate/Server/controller/atsController.js, DevElevate/Server/controller/courseController.js, DevElevate/Server/middleware/authMiddleware.js
Added a line about the ATS in the comments to explain better what it is, in the atsController.js
Fixed some typos.
=> docs: add comments to authentication middleware for clarity

DevElevate/Client/src/components/Settings/Settings.tsx
This PR optimizes the **Account Settings** section UI in **light mode** for a consistent and professional appearance, aligning it with **Security, Notifications, and Preferences** sections.  
Dark mode styles remain unchanged.
---
- Updated **Account Settings container** with `bg-gray-50`, `text-neutral-800`, and `border border-gray-200` for a clean light mode look.  
- Standardized **labels, inputs, and textarea** with `text-neutral-800`, `bg-white`, and consistent spacing.  
- Unified **input borders** using `border-gray-300` (error state → `border-red-500`).  
- Matched **typography and spacing** with other Settings sections.  
---
- Light mode now looks **cohesive, modern, and professional** across all Settings sections.  
- Dark mode styles remain **unchanged**.  
- Build successful: …
=> ✨ PR: Professional Light Mode UI and Dark Mode Optimization for Settings Page

DevElevate/Client/src/components/LearningHub/AIML/ModuleCards.tsx, DevElevate/Client/src/components/LearningHub/AIML/TopicView.tsx, DevElevate/Client/src/components/LearningHub/AIML/moduleContent.tsx, DevElevate/Client/src/components/LearningHub/LearningHub.tsx, DevElevate/Server/index.js, DevElevate/Server/routes/aimlRoutes.js
=> Added content for AI/Ml module 

DevElevate/Client/package-lock.json, DevElevate/Client/package.json, DevElevate/Client/src/components/Profile/UserProfile.tsx, DevElevate/Client/src/main.tsx, DevElevate/Server/controller/userController.js, DevElevate/Server/package-lock.json, DevElevate/Server/package.json, DevElevate/Server/routes/userRoutes.js, DevElevate/Server/utils/passwordChangeLimiter.js
Title:
feat: add password change functionality 😊
feat:add react-hot-tost
Description:
This PR introduces a Password Change feature that allows users to securely update their account passwords. The feature includes:
=> Add password change functionality

DevElevate/Client/src/components/Auth/LoginRegister.tsx
removed the console log of google auth.
=> fixed user payload console log

DevElevate/Server/index.js, DevElevate/Server/middleware/sanitizeMiddleware.js, DevElevate/Server/package-lock.json, DevElevate/Server/package.json
Missing HTML Sanitization (XSS Risk)
The application was missing proper sanitization of HTML input in POST/PUT requests, which could allow XSS (Cross-Site Scripting) attacks. User inputs containing `<script>` tags or unsafe HTML could be executed in the browser.
- Created a **new file** `sanitizeMiddleware.js` inside the existing `middleware` directory.
- Middleware recursively sanitizes:
- Strings
- Nested objects
- Arrays in `req.body`
- Allowed tags: `b`, `i`, `em`, `strong`, `p`, `ul`, `li`, `a`.
- Allowed attributes for `<a>`: `href`, `name`, `target`.
- Allowed schemes: `http`, `https`, `mailto`.
- Integrated middleware **globally in `index.js` (server/app file)** after `express.json()` and `cookieParser()` to protect all POST/PUT/PATCH requests.
- Tested with sample inputs …
=> Fix #435: Added global HTML sanitization middleware to prevent XSS

DevElevate/Client/src/components/Auth/ProtectedRoute.tsx, DevElevate/Client/src/components/Layout/ProfileDropdown.tsx
=> maintenanceMode done

DevElevate/Client/src/App.tsx, DevElevate/Client/src/components/Chatbot/Chatbot.tsx, DevElevate/Client/src/components/Layout/Layout.tsx
remove all the unused components
=> remove extra components in app.txs

DevElevate/Client/src/App.tsx
=> <Route path="/" element={<LandingPage />} />

.github/ISSUE_TEMPLATE/documentation.md
Added a documentation md in .github folder
=> Added documentation

.github/pull_request_template.md
Hi @abhisek2004 , i had added the template for pull request , kindly take a look
=> Add pull request template for contributions

.github/workflows/pr-comment.yml
- Closes #516 
Updated the GitHub Actions workflow to handle more pull request types and improved comment formatting. Adjusted label assignment logic and added checks for PR size.
Updated pr-autocomment file
No
=> Fix the constantly failing PR

DevElevate/Server/controller/adminController.js
Fixes #511 
**Description:**
- This PR improves the performance, readability, and maintainability of the adminController.js file.
---
**🔄 Changes Made**
- Optimized DB calls with Promise.all.
- Standardized response structure and error handling.
- Improved pagination logic for getAdminLogs.
- Reduced redundancy in object creation.
- Added clear sectioning for log and user controllers.
---
**✅ Checklist**
-  Code optimized without breaking functionality
- Response format standardized
- Pagination logic improved
-  Tested all endpoints locally
-  No breaking changes introduced
=> Optimized adminController.js for efficiency and maintainability

DevElevate/Server/controller/adminController.js, DevElevate/Server/controller/atsController.js
Fixes #512 
**Description:**
- This PR optimizes the atsController.js code by improving readability, reducing redundancy, and ensuring consistent logic across ATS scanning.
---
**🔄 Changes Made**
- Simplified section mapping with a dictionary.
- Consolidated score calculation and bonus application.
- Organized suggestions generation into clear blocks.
- Optimized keyword matching logic.
- Improved error handling consistency.
---
**✅ Checklist**
-  Functionality preserved
-  Code readability improved
-  Redundant logic removed
-  Suggestions logic optimized
-  Tested endpoints locally
=> Refactored atsController.js for maintainability and clarity

DevElevate/Server/controller/adminController.js, DevElevate/Server/controller/atsController.js, DevElevate/Server/controller/communityController.js
Fixes #513 
**Description:**
- This PR optimizes the communityController.js file while keeping all functionality intact.
---
**✅ Changes Made**
- Improved code readability and formatting
- Added structured section comments for User Operations and Admin Operations
- Standardized return statements for responses
- Removed redundant code and unused sample data
---
**🔍 Testing**
-  All question-related endpoints tested
- Answer posting and retrieval verified
-  Admin operations (deleteQuestion, markAsResolved, acceptAnswer) tested successfully
=> Refactor communityController.js for readability and consistency

DevElevate/Server/controller/adminController.js, DevElevate/Server/controller/atsController.js, DevElevate/Server/controller/communityController.js, DevElevate/Server/controller/courseController.js
Fixes #514 
**Description:**
- This PR optimizes the courseController.js while maintaining existing functionality.
---
**✅ Changes Made**
- Standardized response messages
- Improved error logging with consistent messages
- Streamlined course and module update logic
- Improved formatting for better readability
---
**🔍 Testing**
- Course creation tested successfully
-  Course and module update tested
-  Fetch all courses tested
-  Delete course and modules tested
=> Refactor courseController.js for better readability and consistency

DevElevate/Client/src/App.tsx, DevElevate/Client/src/components/Layout/ProfileDropdown.tsx, DevElevate/Client/src/components/Settings/AccountSettings.tsx, DevElevate/Client/src/components/Settings/NotificationSettings.tsx, DevElevate/Client/src/components/Settings/ProfileSettings.tsx, DevElevate/Client/src/components/Settings/ThemeSettings.tsx, DevElevate/Client/src/components/Settings/UserSettings.tsx
This pull request implements a comprehensive User Settings/Preferences Page that provides users with a centralized location to manage their account preferences, customize their profile, control notifications, and adjust theme settings.
Closes #555 
- **New Components Created:**
- `UserSettings.tsx` - Main settings page container
- `ProfileSettings.tsx` - Profile customization section
- `NotificationSettings.tsx` - Notification preferences management
- `ThemeSettings.tsx` - Appearance and theme controls
- `SecuritySettings.tsx` - Account security management
- `SettingsNavigation.tsx` - Settings page navigation component
- **UI/UX Improvements:**
- Responsive design for all screen sizes
- Tabbed navigation for different settings sections
- Form validation with real-time feedback
- Loading …
=> feat(settings): Implement User Settings/Preferences Page

DevElevate/Client/package-lock.json, DevElevate/Client/package.json, DevElevate/Client/src/App.tsx, DevElevate/Client/src/components/Dashboard/DailyGoals.tsx, DevElevate/Client/src/components/Dashboard/NewsWidget.tsx, DevElevate/Client/src/components/Dashboard/ProgressWidget.tsx, DevElevate/Client/src/components/Dashboard/QuickActions.tsx, DevElevate/Client/src/components/Dashboard/StatsCards.tsx, DevElevate/Client/src/components/Dashboard/StreakCalendar.tsx, DevElevate/Client/src/components/Quiz/QuizHistory.tsx, DevElevate/Client/src/pages/Landing/components/CTA.tsx, DevElevate/Client/src/pages/Landing/components/CreatorPage.tsx, DevElevate/Client/src/pages/Landing/components/FAQ.tsx, DevElevate/Client/src/pages/Landing/components/Features.tsx, DevElevate/Client/src/pages/Landing/components/Footer.tsx, DevElevate/Client/src/pages/Landing/components/Hero.tsx, DevElevate/Client/src/pages/Landing/components/Testimonials.tsx, DevElevate/Client/src/pages/Notes/FallBackNotes.jsx, DevElevate/Client/src/utils/firebase.ts, package-lock.json
Closes #543.
This PR introduces two key improvements. First, it addresses a critical bug that caused the application to crash on startup if Firebase environment variables weren't configured, blocking local development for contributors.
Second, it enhances the overall user experience by integrating 'Animate on Scroll' (AOS) functionality. This adds a modern, dynamic feel to the application, making the interface more engaging as users navigate through the content.
Global AOS Setup: The aos library has been imported and initialized in Client/src/App.tsx, making animation capabilities available application-wide.
UI Animation Implementation: Added data-aos attributes (e.g., fade-up, zoom-in) to components across the landing page (Hero, Features, Testimonials) and the user dashboard …
=> feat: Implement Animate on Scroll (AOS) & Fix Firebase Init 🚀

DevElevate/Client/src/App.tsx, DevElevate/Client/src/components/PlacementPrep/PlacementPrep.tsx, DevElevate/Client/src/data/companyQuestions.ts, DevElevate/Client/src/pages/Dsa/CompanyQuestionsList.tsx, DevElevate/Client/src/pages/Dsa/CompanyQuestionsPage.tsx, DevElevate/Client/src/pages/Dsa/CompanySelector.tsx, DevElevate/Client/src/pages/Dsa/DsaLanding.tsx, DevElevate/Client/src/pages/Dsa/PracticeProblemsPage.tsx, DevElevate/Client/src/pages/Dsa/QuestionContext.tsx, DevElevate/Client/src/pages/Dsa/data/companyQuestions.ts, DevElevate/Client/src/pages/Dsa/data/flashcards.ts, DevElevate/Client/src/pages/Dsa/data/questions.json, DevElevate/Client/src/pages/Dsa/data/questions.ts, DevElevate/Client/src/types/dsa.ts
Practice curated DSA questions asked by top tech companies. DSA Practice Problems
Solve topic-wise problems to master data structures and algorithms.
=> Company-wise Questions
